/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import knockknockclient.KnockKnockClient;

/**
 *
 * @author pradosman
 */
public class Videos extends javax.swing.JFrame{
    private String cadena;
    private KnockKnockClient client = null;
    
    
    /**
     * Creates new form Videos
     * @param lista
     */
    public Videos(String cadena, KnockKnockClient client) {
        initComponents();
        this.cadena = cadena;
        this.client = client;
        jLabel1.setText(jLabel1.getText() + this.client.getLogin());
        mostrar(this.cadena);
        //verVideo();
    }
    
    public Videos(){}

    public void mostrar(String cadena){   
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                mostrarVideos(listaVideos, cadena);
                return null;
            }
        };
        worker.execute();
    }
    
    public void mostrarVideos(JTable jTable1, String cadena) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String[] strings = cadena.split("#");
        String [] datosUsuario = new String[strings.length];
        
        for(int i = 0; i < strings.length; i++){
            datosUsuario = strings[i].split("@");
            for(int j = 1; j < datosUsuario.length; j++){
                String[] datosVideo = datosUsuario[j].split("&");
                String[] conjuntoDatos = {datosUsuario[0], datosVideo[0], datosVideo[1], datosVideo[2]};
                modelo.addRow(conjuntoDatos);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaVideos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSubir = new javax.swing.JButton();
        jTextTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnVer1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 125, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "ID Video", "Titulo", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(listaVideos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 420));

        textAreaDebug.setColumns(20);
        textAreaDebug.setRows(5);
        jScrollPane2.setViewportView(textAreaDebug);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 880, -1));

        jLabel1.setText("User:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 210, 40));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        btnSubir.setText("Subir video");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jTextTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTituloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 140, -1));

        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 60, 20));

        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 140, -1));

        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 60, 20));

        btnVer1.setText("Ver video");
        btnVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 90, -1));

        jButton1.setText("Borrar video");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        jButton2.setText("Streaming");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser1 = new JFileChooser();
        int seleccion=jFileChooser1.showOpenDialog(this);

        //Si el usuario, pincha en aceptar
        if(seleccion==jFileChooser1.APPROVE_OPTION){
            //Seleccionamos el fichero
            File fichero=jFileChooser1.getSelectedFile();
            client.setFile(fichero);
            //PROTOCOLCRISTOTUBE1.0#VIDEO_UP#TOTAL_SIZE#SIZE_PACKAGE#METADATOS_VIDEO#LOGIN_USER#TITULO#DESCRIPCION
            System.out.println("Elijo fichero");
            System.out.println("Tamaño: "+ fichero.length());
            jFileChooser1.setVisible(false);
            final SwingWorker worker = new SwingWorker(){

                @Override
                protected Object doInBackground() throws Exception {
                    GUI.client.clientOn("PROTOCOLCRISTOTUBE1.0#VIDEO_UP#"+fichero.length()+"#1024#METADATOS_VIDEO#"+client.getLogin()+"#"+jTextTitulo.getText()+"#"+jTextDescripcion.getText());
                    return null;
                }
            };
            worker.execute();
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void jTextTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTituloActionPerformed

    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void btnVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1ActionPerformed
        // TODO add your handling code here:
        String idVideo = (String) this.listaVideos.getValueAt(this.listaVideos.getSelectedRow(), 1);
        System.out.println(idVideo);
        String login = (String) this.listaVideos.getValueAt(this.listaVideos.getSelectedRow(), 0);
        final SwingWorker worker = new SwingWorker(){

            @Override
            protected Object doInBackground() throws Exception {
                GUI.client.clientOn("PROTOCOLCRISTOTUBE1.0#"+login+"#GETVIDEO#"+ idVideo);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnVer1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idVideo = (String) this.listaVideos.getValueAt(this.listaVideos.getSelectedRow(), 1);
        System.out.println(idVideo);
        final SwingWorker worker = new SwingWorker(){

            @Override
            protected Object doInBackground() throws Exception {
                GUI.client.clientOn("PROTOCOLCRISTOTUBE1.0#DELETE_VIDEO#"+ idVideo);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Videos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton btnVer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextTitulo;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listaVideos;
    private javax.swing.JTextArea textAreaDebug;
    // End of variables declaration//GEN-END:variables

}
